/*
mpcc : A fast customized optimization solver.

Copyright (C) 2013-2021 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCESPRO v4.2.0 on Monday, March 15, 2021 at 7:06:10 PM */
#ifndef mpcc_H
#define mpcc_H

#ifndef SOLVER_STDIO_H
#define SOLVER_STDIO_H
#include <stdio.h>
#endif


#ifndef SOLVER_STANDARD_TYPES
#define SOLVER_STANDARD_TYPES

typedef signed char solver_int8_signed;
typedef unsigned char solver_int8_unsigned;
typedef char solver_int8_default;
typedef signed short int solver_int16_signed;
typedef unsigned short int solver_int16_unsigned;
typedef short int solver_int16_default;
typedef signed int solver_int32_signed;
typedef unsigned int solver_int32_unsigned;
typedef int solver_int32_default;
typedef signed long long int solver_int64_signed;
typedef unsigned long long int solver_int64_unsigned;
typedef long long int solver_int64_default;

#endif


/* DATA TYPE ------------------------------------------------------------*/
typedef double mpcc_float;


typedef double mpccinterface_float;

/* SOLVER SETTINGS ------------------------------------------------------*/

/* MISRA-C compliance */
#ifndef MISRA_C_mpcc
#define MISRA_C_mpcc (0)
#endif

/* restrict code */
#ifndef RESTRICT_CODE_mpcc
#define RESTRICT_CODE_mpcc (0)
#endif

/* print level */
#ifndef SET_PRINTLEVEL_mpcc
#define SET_PRINTLEVEL_mpcc    (0)
#endif

/* timing */
#ifndef SET_TIMING_mpcc
#define SET_TIMING_mpcc    (1)
#endif

/* Numeric Warnings */
/* #define PRINTNUMERICALWARNINGS */

/* maximum number of iterations  */
#define SET_MAXIT_mpcc         (200)	

/* scaling factor of line search (affine direction) */
#define SET_LS_SCALE_AFF_mpcc  (mpcc_float)(0.9)      

/* scaling factor of line search (combined direction) */
#define SET_LS_SCALE_mpcc      (mpcc_float)(0.95)  

/* minimum required step size in each iteration */
#define SET_LS_MINSTEP_mpcc    (mpcc_float)(1E-08)

/* maximum step size (combined direction) */
#define SET_LS_MAXSTEP_mpcc    (mpcc_float)(0.995)

/* desired relative duality gap */
#define SET_ACC_RDGAP_mpcc     (mpcc_float)(0.0001)

/* desired maximum residual on equality constraints */
#define SET_ACC_RESEQ_mpcc     (mpcc_float)(1E-06)

/* desired maximum residual on inequality constraints */
#define SET_ACC_RESINEQ_mpcc   (mpcc_float)(1E-06)

/* desired maximum violation of complementarity */
#define SET_ACC_KKTCOMPL_mpcc  (mpcc_float)(1E-06)

/* desired maximum violation of stationarity (only checked if value is > 0) */
#define SET_ACC_KKTSTAT_mpcc  (mpcc_float)(-1)

/* RETURN CODES----------------------------------------------------------*/
/* solver has converged within desired accuracy */
#define OPTIMAL_mpcc      (1)

/* maximum number of iterations has been reached */
#define MAXITREACHED_mpcc (0)

/* solver has stopped due to a timeout */
#define TIMEOUT_mpcc   (2)

/* no progress in line search possible */
#define NOPROGRESS_mpcc   (-7)

/* fatal internal error - nans occurring */
#define NAN_mpcc  (-10)

/* invalid values in parameters */
#define PARAM_VALUE_ERROR_mpcc   (-11)

/* too small timeout given */
#define INVALID_TIMEOUT_mpcc   (-12)

/* licensing error - solver not valid on this machine */
#define LICENSE_ERROR_mpcc  (-100)


/* PARAMETERS -----------------------------------------------------------*/
/* fill this with data before calling the solver! */
typedef struct mpcc_params
{
    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H01[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H02[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H03[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H04[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H05[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H06[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H07[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H08[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H09[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H10[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H11[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H12[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H13[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H14[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H15[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H16[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H17[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H18[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H19[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H20[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H21[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H22[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H23[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H24[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H25[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H26[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H27[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H28[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H29[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H30[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H31[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H32[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H33[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H34[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H35[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H36[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H37[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H38[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H39[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H40[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H41[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H42[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H43[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H44[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H45[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H46[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H47[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H48[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H49[196];

    /* matrix of size [14 x 14] (column major format) */
    mpcc_float H50[196];

    /* vector of size 14 */
    mpcc_float f01[14];

    /* vector of size 14 */
    mpcc_float f02[14];

    /* vector of size 14 */
    mpcc_float f03[14];

    /* vector of size 14 */
    mpcc_float f04[14];

    /* vector of size 14 */
    mpcc_float f05[14];

    /* vector of size 14 */
    mpcc_float f06[14];

    /* vector of size 14 */
    mpcc_float f07[14];

    /* vector of size 14 */
    mpcc_float f08[14];

    /* vector of size 14 */
    mpcc_float f09[14];

    /* vector of size 14 */
    mpcc_float f10[14];

    /* vector of size 14 */
    mpcc_float f11[14];

    /* vector of size 14 */
    mpcc_float f12[14];

    /* vector of size 14 */
    mpcc_float f13[14];

    /* vector of size 14 */
    mpcc_float f14[14];

    /* vector of size 14 */
    mpcc_float f15[14];

    /* vector of size 14 */
    mpcc_float f16[14];

    /* vector of size 14 */
    mpcc_float f17[14];

    /* vector of size 14 */
    mpcc_float f18[14];

    /* vector of size 14 */
    mpcc_float f19[14];

    /* vector of size 14 */
    mpcc_float f20[14];

    /* vector of size 14 */
    mpcc_float f21[14];

    /* vector of size 14 */
    mpcc_float f22[14];

    /* vector of size 14 */
    mpcc_float f23[14];

    /* vector of size 14 */
    mpcc_float f24[14];

    /* vector of size 14 */
    mpcc_float f25[14];

    /* vector of size 14 */
    mpcc_float f26[14];

    /* vector of size 14 */
    mpcc_float f27[14];

    /* vector of size 14 */
    mpcc_float f28[14];

    /* vector of size 14 */
    mpcc_float f29[14];

    /* vector of size 14 */
    mpcc_float f30[14];

    /* vector of size 14 */
    mpcc_float f31[14];

    /* vector of size 14 */
    mpcc_float f32[14];

    /* vector of size 14 */
    mpcc_float f33[14];

    /* vector of size 14 */
    mpcc_float f34[14];

    /* vector of size 14 */
    mpcc_float f35[14];

    /* vector of size 14 */
    mpcc_float f36[14];

    /* vector of size 14 */
    mpcc_float f37[14];

    /* vector of size 14 */
    mpcc_float f38[14];

    /* vector of size 14 */
    mpcc_float f39[14];

    /* vector of size 14 */
    mpcc_float f40[14];

    /* vector of size 14 */
    mpcc_float f41[14];

    /* vector of size 14 */
    mpcc_float f42[14];

    /* vector of size 14 */
    mpcc_float f43[14];

    /* vector of size 14 */
    mpcc_float f44[14];

    /* vector of size 14 */
    mpcc_float f45[14];

    /* vector of size 14 */
    mpcc_float f46[14];

    /* vector of size 14 */
    mpcc_float f47[14];

    /* vector of size 14 */
    mpcc_float f48[14];

    /* vector of size 14 */
    mpcc_float f49[14];

    /* vector of size 14 */
    mpcc_float f50[14];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A01[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A02[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A03[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A04[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A05[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A06[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A07[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A08[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A09[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A10[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A11[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A12[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A13[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A14[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A15[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A16[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A17[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A18[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A19[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A20[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A21[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A22[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A23[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A24[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A25[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A26[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A27[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A28[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A29[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A30[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A31[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A32[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A33[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A34[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A35[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A36[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A37[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A38[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A39[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A40[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A41[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A42[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A43[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A44[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A45[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A46[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A47[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A48[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A49[28];

    /* matrix of size [2 x 14] (column major format) */
    mpcc_float A50[28];

    /* vector of size 2 */
    mpcc_float b01[2];

    /* vector of size 2 */
    mpcc_float b02[2];

    /* vector of size 2 */
    mpcc_float b03[2];

    /* vector of size 2 */
    mpcc_float b04[2];

    /* vector of size 2 */
    mpcc_float b05[2];

    /* vector of size 2 */
    mpcc_float b06[2];

    /* vector of size 2 */
    mpcc_float b07[2];

    /* vector of size 2 */
    mpcc_float b08[2];

    /* vector of size 2 */
    mpcc_float b09[2];

    /* vector of size 2 */
    mpcc_float b10[2];

    /* vector of size 2 */
    mpcc_float b11[2];

    /* vector of size 2 */
    mpcc_float b12[2];

    /* vector of size 2 */
    mpcc_float b13[2];

    /* vector of size 2 */
    mpcc_float b14[2];

    /* vector of size 2 */
    mpcc_float b15[2];

    /* vector of size 2 */
    mpcc_float b16[2];

    /* vector of size 2 */
    mpcc_float b17[2];

    /* vector of size 2 */
    mpcc_float b18[2];

    /* vector of size 2 */
    mpcc_float b19[2];

    /* vector of size 2 */
    mpcc_float b20[2];

    /* vector of size 2 */
    mpcc_float b21[2];

    /* vector of size 2 */
    mpcc_float b22[2];

    /* vector of size 2 */
    mpcc_float b23[2];

    /* vector of size 2 */
    mpcc_float b24[2];

    /* vector of size 2 */
    mpcc_float b25[2];

    /* vector of size 2 */
    mpcc_float b26[2];

    /* vector of size 2 */
    mpcc_float b27[2];

    /* vector of size 2 */
    mpcc_float b28[2];

    /* vector of size 2 */
    mpcc_float b29[2];

    /* vector of size 2 */
    mpcc_float b30[2];

    /* vector of size 2 */
    mpcc_float b31[2];

    /* vector of size 2 */
    mpcc_float b32[2];

    /* vector of size 2 */
    mpcc_float b33[2];

    /* vector of size 2 */
    mpcc_float b34[2];

    /* vector of size 2 */
    mpcc_float b35[2];

    /* vector of size 2 */
    mpcc_float b36[2];

    /* vector of size 2 */
    mpcc_float b37[2];

    /* vector of size 2 */
    mpcc_float b38[2];

    /* vector of size 2 */
    mpcc_float b39[2];

    /* vector of size 2 */
    mpcc_float b40[2];

    /* vector of size 2 */
    mpcc_float b41[2];

    /* vector of size 2 */
    mpcc_float b42[2];

    /* vector of size 2 */
    mpcc_float b43[2];

    /* vector of size 2 */
    mpcc_float b44[2];

    /* vector of size 2 */
    mpcc_float b45[2];

    /* vector of size 2 */
    mpcc_float b46[2];

    /* vector of size 2 */
    mpcc_float b47[2];

    /* vector of size 2 */
    mpcc_float b48[2];

    /* vector of size 2 */
    mpcc_float b49[2];

    /* vector of size 2 */
    mpcc_float b50[2];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C01[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C02[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C03[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C04[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C05[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C06[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C07[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C08[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C09[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C10[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C11[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C12[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C13[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C14[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C15[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C16[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C17[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C18[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C19[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C20[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C21[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C22[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C23[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C24[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C25[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C26[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C27[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C28[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C29[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C30[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C31[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C32[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C33[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C34[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C35[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C36[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C37[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C38[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C39[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C40[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C41[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C42[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C43[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C44[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C45[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C46[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C47[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C48[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float C49[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D01[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D02[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D03[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D04[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D05[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D06[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D07[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D08[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D09[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D10[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D11[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D12[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D13[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D14[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D15[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D16[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D17[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D18[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D19[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D20[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D21[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D22[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D23[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D24[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D25[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D26[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D27[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D28[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D29[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D30[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D31[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D32[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D33[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D34[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D35[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D36[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D37[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D38[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D39[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D40[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D41[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D42[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D43[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D44[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D45[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D46[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D47[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D48[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D49[154];

    /* matrix of size [11 x 14] (column major format) */
    mpcc_float D50[154];

    /* vector of size 11 */
    mpcc_float c02[11];

    /* vector of size 11 */
    mpcc_float c03[11];

    /* vector of size 11 */
    mpcc_float c04[11];

    /* vector of size 11 */
    mpcc_float c05[11];

    /* vector of size 11 */
    mpcc_float c06[11];

    /* vector of size 11 */
    mpcc_float c07[11];

    /* vector of size 11 */
    mpcc_float c08[11];

    /* vector of size 11 */
    mpcc_float c09[11];

    /* vector of size 11 */
    mpcc_float c10[11];

    /* vector of size 11 */
    mpcc_float c11[11];

    /* vector of size 11 */
    mpcc_float c12[11];

    /* vector of size 11 */
    mpcc_float c13[11];

    /* vector of size 11 */
    mpcc_float c14[11];

    /* vector of size 11 */
    mpcc_float c15[11];

    /* vector of size 11 */
    mpcc_float c16[11];

    /* vector of size 11 */
    mpcc_float c17[11];

    /* vector of size 11 */
    mpcc_float c18[11];

    /* vector of size 11 */
    mpcc_float c19[11];

    /* vector of size 11 */
    mpcc_float c20[11];

    /* vector of size 11 */
    mpcc_float c21[11];

    /* vector of size 11 */
    mpcc_float c22[11];

    /* vector of size 11 */
    mpcc_float c23[11];

    /* vector of size 11 */
    mpcc_float c24[11];

    /* vector of size 11 */
    mpcc_float c25[11];

    /* vector of size 11 */
    mpcc_float c26[11];

    /* vector of size 11 */
    mpcc_float c27[11];

    /* vector of size 11 */
    mpcc_float c28[11];

    /* vector of size 11 */
    mpcc_float c29[11];

    /* vector of size 11 */
    mpcc_float c30[11];

    /* vector of size 11 */
    mpcc_float c31[11];

    /* vector of size 11 */
    mpcc_float c32[11];

    /* vector of size 11 */
    mpcc_float c33[11];

    /* vector of size 11 */
    mpcc_float c34[11];

    /* vector of size 11 */
    mpcc_float c35[11];

    /* vector of size 11 */
    mpcc_float c36[11];

    /* vector of size 11 */
    mpcc_float c37[11];

    /* vector of size 11 */
    mpcc_float c38[11];

    /* vector of size 11 */
    mpcc_float c39[11];

    /* vector of size 11 */
    mpcc_float c40[11];

    /* vector of size 11 */
    mpcc_float c41[11];

    /* vector of size 11 */
    mpcc_float c42[11];

    /* vector of size 11 */
    mpcc_float c43[11];

    /* vector of size 11 */
    mpcc_float c44[11];

    /* vector of size 11 */
    mpcc_float c45[11];

    /* vector of size 11 */
    mpcc_float c46[11];

    /* vector of size 11 */
    mpcc_float c47[11];

    /* vector of size 11 */
    mpcc_float c48[11];

    /* vector of size 11 */
    mpcc_float c49[11];

    /* vector of size 11 */
    mpcc_float c50[11];

    /* vector of size 11 */
    mpcc_float minusA_times_x0[11];

} mpcc_params;


/* OUTPUTS --------------------------------------------------------------*/
/* the desired variables are put here by the solver */
typedef struct mpcc_output
{
    /* vector of size 700 */
    mpcc_float u0[700];

} mpcc_output;


/* SOLVER INFO ----------------------------------------------------------*/
/* diagnostic data from last interior point step */
typedef struct mpcc_info
{
    /* iteration number */
    solver_int32_default it;

	/* number of iterations needed to optimality (branch-and-bound) */
	solver_int32_default it2opt;
	
    /* inf-norm of equality constraint residuals */
    mpcc_float res_eq;
	
    /* inf-norm of inequality constraint residuals */
    mpcc_float res_ineq;

    /* primal objective */
    mpcc_float pobj;	
	
    /* dual objective */
    mpcc_float dobj;	

    /* duality gap := pobj - dobj */
    mpcc_float dgap;		
	
    /* relative duality gap := |dgap / pobj | */
    mpcc_float rdgap;		

	/* infinity norm of gradient of Lagrangian*/
	mpcc_float gradient_lag_norm;

    /* duality measure */
    mpcc_float mu;

	/* duality measure (after affine step) */
    mpcc_float mu_aff;
	
    /* centering parameter */
    mpcc_float sigma;
	
    /* number of backtracking line search steps (affine direction) */
    solver_int32_default lsit_aff;
    
    /* number of backtracking line search steps (combined direction) */
    solver_int32_default lsit_cc;
    
    /* step size (affine direction) */
    mpcc_float step_aff;
    
    /* step size (combined direction) */
    mpcc_float step_cc;    

	/* solvertime */
	mpcc_float solvetime;   

} mpcc_info;









/* SOLVER FUNCTION DEFINITION -------------------------------------------*/
/* Time of Solver Generation: (UTC) Monday, March 15, 2021 7:06:12 PM */
/* User License expires on: (UTC) Saturday, August 28, 2021 10:00:00 PM (approx.) (at the time of code generation) */
/* Solver Static License expires on: (UTC) Saturday, August 28, 2021 10:00:00 PM (approx.) */
/* Solver Generation Request Id: ec8b7033-bac0-49d4-807e-11fc23724746 */
/* examine exitflag before using the result! */
#ifdef __cplusplus
extern "C" {
#endif
extern solver_int32_default mpcc_solve(mpcc_params *params, mpcc_output *output, mpcc_info *info, FILE *fs);


#ifdef __cplusplus
}
#endif

#endif
