import numpy
import ctypes

name = "mpcc"
requires_callback = False
lib = "lib/libmpcc.so"
lib_static = "lib/libmpcc.a"
c_header = "include/mpcc.h"

# Parameter             | Type    | Scalar type      | Ctypes type    | Numpy type   | Shape     | Len
params = \
[("H01"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H02"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H03"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H04"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H05"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H06"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H07"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H08"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H09"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H10"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H11"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H12"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H13"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H14"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H15"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H16"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H17"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H18"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H19"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("H20"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,  13),  169),
 ("f01"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f02"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f03"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f04"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f05"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f06"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f07"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f08"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f09"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f10"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f11"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f12"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f13"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f14"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f15"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f16"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f17"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f18"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f19"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("f20"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 13,   1),   13),
 ("A01"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A02"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A03"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A04"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A05"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A06"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A07"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A08"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A09"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A10"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A11"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A12"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A13"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A14"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A15"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A16"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A17"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A18"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A19"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("A20"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  13),   26),
 ("b01"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b02"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b03"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b04"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b05"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b06"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b07"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b08"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b09"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b10"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b11"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b12"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b13"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b14"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b15"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b16"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b17"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b18"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b19"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b20"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("C01"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C02"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C03"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C04"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C05"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C06"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C07"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C08"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C09"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C10"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C11"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C12"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C13"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C14"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C15"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C16"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C17"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C18"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("C19"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D01"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D02"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D03"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D04"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D05"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D06"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D07"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D08"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D09"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D10"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D11"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D12"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D13"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D14"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D15"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D16"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D17"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D18"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D19"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("D20"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  13),  130),
 ("c02"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c03"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c04"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c05"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c06"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c07"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c08"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c09"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c10"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c11"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c12"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c13"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c14"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c15"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c16"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c17"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c18"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c19"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c20"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("minusA_times_x0"     , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10)]

# Output                | Type    | Scalar type      | Ctypes type    | Numpy type   | Shape     | Len
outputs = \
[("u0"                  , ""      , ""               , ctypes.c_double, numpy.float64,     ( 13,),  260)]

# Info Struct Fields
info = \
[('it', ctypes.c_int32),
('it2opt', ctypes.c_int32),
('res_eq', ctypes.c_double),
('res_ineq', ctypes.c_double),
('pobj', ctypes.c_double),
('dobj', ctypes.c_double),
('dgap', ctypes.c_double),
('rdgap', ctypes.c_double),
('gradient_lag_norm', ctypes.c_double),
('mu', ctypes.c_double),
('mu_aff', ctypes.c_double),
('sigma', ctypes.c_double),
('lsit_aff', ctypes.c_int32),
('lsit_cc', ctypes.c_int32),
('step_aff', ctypes.c_double),
('step_cc', ctypes.c_double),
('solvetime', ctypes.c_double)
]