#mpcc : A fast customized optimization solver.
#
#Copyright (C) 2013-2021 EMBOTECH AG [info@embotech.com]. All rights reserved.
#
#
#This software is intended for simulation and testing purposes only. 
#Use of this software for any commercial purpose is prohibited.
#
#This program is distributed in the hope that it will be useful.
#EMBOTECH makes NO WARRANTIES with respect to the use of the software 
#without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
#PARTICULAR PURPOSE. 
#
#EMBOTECH shall not have any liability for any damage arising from the use
#of the software.
#
#This Agreement shall exclusively be governed by and interpreted in 
#accordance with the laws of Switzerland, excluding its principles
#of conflict of laws. The Courts of Zurich-City shall have exclusive 
#jurisdiction in case of any dispute.
#
#def __init__():
'''
a Python wrapper for a fast solver generated by FORCESPRO v4.2.1

   OUTPUT = mpcc_py.mpcc_solve(PARAMS) solves a multistage problem
   subject to the parameters supplied in the following dictionary:
       PARAMS['H01'] - matrix of size [13 x 13]
       PARAMS['H02'] - matrix of size [13 x 13]
       PARAMS['H03'] - matrix of size [13 x 13]
       PARAMS['H04'] - matrix of size [13 x 13]
       PARAMS['H05'] - matrix of size [13 x 13]
       PARAMS['H06'] - matrix of size [13 x 13]
       PARAMS['H07'] - matrix of size [13 x 13]
       PARAMS['H08'] - matrix of size [13 x 13]
       PARAMS['H09'] - matrix of size [13 x 13]
       PARAMS['H10'] - matrix of size [13 x 13]
       PARAMS['H11'] - matrix of size [13 x 13]
       PARAMS['H12'] - matrix of size [13 x 13]
       PARAMS['H13'] - matrix of size [13 x 13]
       PARAMS['H14'] - matrix of size [13 x 13]
       PARAMS['H15'] - matrix of size [13 x 13]
       PARAMS['H16'] - matrix of size [13 x 13]
       PARAMS['H17'] - matrix of size [13 x 13]
       PARAMS['H18'] - matrix of size [13 x 13]
       PARAMS['H19'] - matrix of size [13 x 13]
       PARAMS['H20'] - matrix of size [13 x 13]
       PARAMS['f01'] - column vector of length 13
       PARAMS['f02'] - column vector of length 13
       PARAMS['f03'] - column vector of length 13
       PARAMS['f04'] - column vector of length 13
       PARAMS['f05'] - column vector of length 13
       PARAMS['f06'] - column vector of length 13
       PARAMS['f07'] - column vector of length 13
       PARAMS['f08'] - column vector of length 13
       PARAMS['f09'] - column vector of length 13
       PARAMS['f10'] - column vector of length 13
       PARAMS['f11'] - column vector of length 13
       PARAMS['f12'] - column vector of length 13
       PARAMS['f13'] - column vector of length 13
       PARAMS['f14'] - column vector of length 13
       PARAMS['f15'] - column vector of length 13
       PARAMS['f16'] - column vector of length 13
       PARAMS['f17'] - column vector of length 13
       PARAMS['f18'] - column vector of length 13
       PARAMS['f19'] - column vector of length 13
       PARAMS['f20'] - column vector of length 13
       PARAMS['A01'] - matrix of size [2 x 13]
       PARAMS['A02'] - matrix of size [2 x 13]
       PARAMS['A03'] - matrix of size [2 x 13]
       PARAMS['A04'] - matrix of size [2 x 13]
       PARAMS['A05'] - matrix of size [2 x 13]
       PARAMS['A06'] - matrix of size [2 x 13]
       PARAMS['A07'] - matrix of size [2 x 13]
       PARAMS['A08'] - matrix of size [2 x 13]
       PARAMS['A09'] - matrix of size [2 x 13]
       PARAMS['A10'] - matrix of size [2 x 13]
       PARAMS['A11'] - matrix of size [2 x 13]
       PARAMS['A12'] - matrix of size [2 x 13]
       PARAMS['A13'] - matrix of size [2 x 13]
       PARAMS['A14'] - matrix of size [2 x 13]
       PARAMS['A15'] - matrix of size [2 x 13]
       PARAMS['A16'] - matrix of size [2 x 13]
       PARAMS['A17'] - matrix of size [2 x 13]
       PARAMS['A18'] - matrix of size [2 x 13]
       PARAMS['A19'] - matrix of size [2 x 13]
       PARAMS['A20'] - matrix of size [2 x 13]
       PARAMS['b01'] - column vector of length 2
       PARAMS['b02'] - column vector of length 2
       PARAMS['b03'] - column vector of length 2
       PARAMS['b04'] - column vector of length 2
       PARAMS['b05'] - column vector of length 2
       PARAMS['b06'] - column vector of length 2
       PARAMS['b07'] - column vector of length 2
       PARAMS['b08'] - column vector of length 2
       PARAMS['b09'] - column vector of length 2
       PARAMS['b10'] - column vector of length 2
       PARAMS['b11'] - column vector of length 2
       PARAMS['b12'] - column vector of length 2
       PARAMS['b13'] - column vector of length 2
       PARAMS['b14'] - column vector of length 2
       PARAMS['b15'] - column vector of length 2
       PARAMS['b16'] - column vector of length 2
       PARAMS['b17'] - column vector of length 2
       PARAMS['b18'] - column vector of length 2
       PARAMS['b19'] - column vector of length 2
       PARAMS['b20'] - column vector of length 2
       PARAMS['C01'] - matrix of size [10 x 13]
       PARAMS['C02'] - matrix of size [10 x 13]
       PARAMS['C03'] - matrix of size [10 x 13]
       PARAMS['C04'] - matrix of size [10 x 13]
       PARAMS['C05'] - matrix of size [10 x 13]
       PARAMS['C06'] - matrix of size [10 x 13]
       PARAMS['C07'] - matrix of size [10 x 13]
       PARAMS['C08'] - matrix of size [10 x 13]
       PARAMS['C09'] - matrix of size [10 x 13]
       PARAMS['C10'] - matrix of size [10 x 13]
       PARAMS['C11'] - matrix of size [10 x 13]
       PARAMS['C12'] - matrix of size [10 x 13]
       PARAMS['C13'] - matrix of size [10 x 13]
       PARAMS['C14'] - matrix of size [10 x 13]
       PARAMS['C15'] - matrix of size [10 x 13]
       PARAMS['C16'] - matrix of size [10 x 13]
       PARAMS['C17'] - matrix of size [10 x 13]
       PARAMS['C18'] - matrix of size [10 x 13]
       PARAMS['C19'] - matrix of size [10 x 13]
       PARAMS['D01'] - matrix of size [10 x 13]
       PARAMS['D02'] - matrix of size [10 x 13]
       PARAMS['D03'] - matrix of size [10 x 13]
       PARAMS['D04'] - matrix of size [10 x 13]
       PARAMS['D05'] - matrix of size [10 x 13]
       PARAMS['D06'] - matrix of size [10 x 13]
       PARAMS['D07'] - matrix of size [10 x 13]
       PARAMS['D08'] - matrix of size [10 x 13]
       PARAMS['D09'] - matrix of size [10 x 13]
       PARAMS['D10'] - matrix of size [10 x 13]
       PARAMS['D11'] - matrix of size [10 x 13]
       PARAMS['D12'] - matrix of size [10 x 13]
       PARAMS['D13'] - matrix of size [10 x 13]
       PARAMS['D14'] - matrix of size [10 x 13]
       PARAMS['D15'] - matrix of size [10 x 13]
       PARAMS['D16'] - matrix of size [10 x 13]
       PARAMS['D17'] - matrix of size [10 x 13]
       PARAMS['D18'] - matrix of size [10 x 13]
       PARAMS['D19'] - matrix of size [10 x 13]
       PARAMS['D20'] - matrix of size [10 x 13]
       PARAMS['c02'] - column vector of length 10
       PARAMS['c03'] - column vector of length 10
       PARAMS['c04'] - column vector of length 10
       PARAMS['c05'] - column vector of length 10
       PARAMS['c06'] - column vector of length 10
       PARAMS['c07'] - column vector of length 10
       PARAMS['c08'] - column vector of length 10
       PARAMS['c09'] - column vector of length 10
       PARAMS['c10'] - column vector of length 10
       PARAMS['c11'] - column vector of length 10
       PARAMS['c12'] - column vector of length 10
       PARAMS['c13'] - column vector of length 10
       PARAMS['c14'] - column vector of length 10
       PARAMS['c15'] - column vector of length 10
       PARAMS['c16'] - column vector of length 10
       PARAMS['c17'] - column vector of length 10
       PARAMS['c18'] - column vector of length 10
       PARAMS['c19'] - column vector of length 10
       PARAMS['c20'] - column vector of length 10
       PARAMS['minusA_times_x0'] - column vector of length 10

   OUTPUT returns the values of the last iteration of the solver where
       OUTPUT['u0'] - column vector of size 260

   [OUTPUT, EXITFLAG] = mpcc_py.mpcc_solve(PARAMS) returns additionally
   the integer EXITFLAG indicating the state of the solution with 
       1 - Optimal solution has been found (subject to desired accuracy)
       2 - (only branch-and-bound) A feasible point has been identified for which the objective value is no more than codeoptions.mip.mipgap*100 per cent worse than the global optimum 
       0 - Timeout - maximum number of iterations reached
      -1 - (only branch-and-bound) Infeasible problem (problems solving the root relaxation to the desired accuracy)
      -2 - (only branch-and-bound) Out of memory - cannot fit branch and bound nodes into pre-allocated memory.
      -6 - NaN or INF occured during evaluation of functions and derivatives. Please check your initial guess.
      -7 - Method could not progress. Problem may be infeasible. Run FORCESdiagnostics on your problem to check for most common errors in the formulation.
     -10 - The convex solver could not proceed due to an internal error
    -100 - License error

   [OUTPUT, EXITFLAG, INFO] = mpcc_py.mpcc_solve(PARAMS) returns 
   additional information about the last iterate:
       INFO.it        - number of iterations that lead to this result
       INFO.it2opt    - number of convex solves
       INFO.res_eq    - max. equality constraint residual
       INFO.res_ineq  - max. inequality constraint residual
       INFO.pobj      - primal objective
       INFO.dobj      - dual objective
       INFO.dgap      - duality gap := pobj - dobj
       INFO.rdgap     - relative duality gap := |dgap / pobj|
       INFO.gradient_lag_norm - infinity norm of gradient of Lagrangian
       INFO.mu        - duality measure
       INFO.sigma     - centering parameter
       INFO.lsit_aff  - iterations of affine line search
       INFO.lsit_cc   - iterations of line search (combined direction)
       INFO.step_aff  - step size (affine direction)
       INFO.step_cc   - step size (centering direction)
       INFO.solvetime - Time needed for solve (wall clock time)

 See also COPYING

'''

import ctypes
import os
import numpy as np
import numpy.ctypeslib as npct
import sys

#_lib = ctypes.CDLL(os.path.join(os.getcwd(),'mpcc/lib/mpcc.so')) 
try:
    _lib = ctypes.CDLL(os.path.join(os.path.dirname(os.path.abspath(__file__)),'mpcc/lib/mpcc.so'))
    csolver = getattr(_lib,'mpcc_solve')
except:
    _lib = ctypes.CDLL(os.path.join(os.path.dirname(os.path.abspath(__file__)),'mpcc/lib/libmpcc.so'))
    csolver = getattr(_lib,'mpcc_solve')

class mpcc_params_ctypes(ctypes.Structure):
#    @classmethod
#    def from_param(self):
#        return self
    _fields_ = [('H01', ctypes.c_double * 169),
('H02', ctypes.c_double * 169),
('H03', ctypes.c_double * 169),
('H04', ctypes.c_double * 169),
('H05', ctypes.c_double * 169),
('H06', ctypes.c_double * 169),
('H07', ctypes.c_double * 169),
('H08', ctypes.c_double * 169),
('H09', ctypes.c_double * 169),
('H10', ctypes.c_double * 169),
('H11', ctypes.c_double * 169),
('H12', ctypes.c_double * 169),
('H13', ctypes.c_double * 169),
('H14', ctypes.c_double * 169),
('H15', ctypes.c_double * 169),
('H16', ctypes.c_double * 169),
('H17', ctypes.c_double * 169),
('H18', ctypes.c_double * 169),
('H19', ctypes.c_double * 169),
('H20', ctypes.c_double * 169),
('f01', ctypes.c_double * 13),
('f02', ctypes.c_double * 13),
('f03', ctypes.c_double * 13),
('f04', ctypes.c_double * 13),
('f05', ctypes.c_double * 13),
('f06', ctypes.c_double * 13),
('f07', ctypes.c_double * 13),
('f08', ctypes.c_double * 13),
('f09', ctypes.c_double * 13),
('f10', ctypes.c_double * 13),
('f11', ctypes.c_double * 13),
('f12', ctypes.c_double * 13),
('f13', ctypes.c_double * 13),
('f14', ctypes.c_double * 13),
('f15', ctypes.c_double * 13),
('f16', ctypes.c_double * 13),
('f17', ctypes.c_double * 13),
('f18', ctypes.c_double * 13),
('f19', ctypes.c_double * 13),
('f20', ctypes.c_double * 13),
('A01', ctypes.c_double * 26),
('A02', ctypes.c_double * 26),
('A03', ctypes.c_double * 26),
('A04', ctypes.c_double * 26),
('A05', ctypes.c_double * 26),
('A06', ctypes.c_double * 26),
('A07', ctypes.c_double * 26),
('A08', ctypes.c_double * 26),
('A09', ctypes.c_double * 26),
('A10', ctypes.c_double * 26),
('A11', ctypes.c_double * 26),
('A12', ctypes.c_double * 26),
('A13', ctypes.c_double * 26),
('A14', ctypes.c_double * 26),
('A15', ctypes.c_double * 26),
('A16', ctypes.c_double * 26),
('A17', ctypes.c_double * 26),
('A18', ctypes.c_double * 26),
('A19', ctypes.c_double * 26),
('A20', ctypes.c_double * 26),
('b01', ctypes.c_double * 2),
('b02', ctypes.c_double * 2),
('b03', ctypes.c_double * 2),
('b04', ctypes.c_double * 2),
('b05', ctypes.c_double * 2),
('b06', ctypes.c_double * 2),
('b07', ctypes.c_double * 2),
('b08', ctypes.c_double * 2),
('b09', ctypes.c_double * 2),
('b10', ctypes.c_double * 2),
('b11', ctypes.c_double * 2),
('b12', ctypes.c_double * 2),
('b13', ctypes.c_double * 2),
('b14', ctypes.c_double * 2),
('b15', ctypes.c_double * 2),
('b16', ctypes.c_double * 2),
('b17', ctypes.c_double * 2),
('b18', ctypes.c_double * 2),
('b19', ctypes.c_double * 2),
('b20', ctypes.c_double * 2),
('C01', ctypes.c_double * 130),
('C02', ctypes.c_double * 130),
('C03', ctypes.c_double * 130),
('C04', ctypes.c_double * 130),
('C05', ctypes.c_double * 130),
('C06', ctypes.c_double * 130),
('C07', ctypes.c_double * 130),
('C08', ctypes.c_double * 130),
('C09', ctypes.c_double * 130),
('C10', ctypes.c_double * 130),
('C11', ctypes.c_double * 130),
('C12', ctypes.c_double * 130),
('C13', ctypes.c_double * 130),
('C14', ctypes.c_double * 130),
('C15', ctypes.c_double * 130),
('C16', ctypes.c_double * 130),
('C17', ctypes.c_double * 130),
('C18', ctypes.c_double * 130),
('C19', ctypes.c_double * 130),
('D01', ctypes.c_double * 130),
('D02', ctypes.c_double * 130),
('D03', ctypes.c_double * 130),
('D04', ctypes.c_double * 130),
('D05', ctypes.c_double * 130),
('D06', ctypes.c_double * 130),
('D07', ctypes.c_double * 130),
('D08', ctypes.c_double * 130),
('D09', ctypes.c_double * 130),
('D10', ctypes.c_double * 130),
('D11', ctypes.c_double * 130),
('D12', ctypes.c_double * 130),
('D13', ctypes.c_double * 130),
('D14', ctypes.c_double * 130),
('D15', ctypes.c_double * 130),
('D16', ctypes.c_double * 130),
('D17', ctypes.c_double * 130),
('D18', ctypes.c_double * 130),
('D19', ctypes.c_double * 130),
('D20', ctypes.c_double * 130),
('c02', ctypes.c_double * 10),
('c03', ctypes.c_double * 10),
('c04', ctypes.c_double * 10),
('c05', ctypes.c_double * 10),
('c06', ctypes.c_double * 10),
('c07', ctypes.c_double * 10),
('c08', ctypes.c_double * 10),
('c09', ctypes.c_double * 10),
('c10', ctypes.c_double * 10),
('c11', ctypes.c_double * 10),
('c12', ctypes.c_double * 10),
('c13', ctypes.c_double * 10),
('c14', ctypes.c_double * 10),
('c15', ctypes.c_double * 10),
('c16', ctypes.c_double * 10),
('c17', ctypes.c_double * 10),
('c18', ctypes.c_double * 10),
('c19', ctypes.c_double * 10),
('c20', ctypes.c_double * 10),
('minusA_times_x0', ctypes.c_double * 10),
]

mpcc_params = {'H01' : np.array([]),
'H02' : np.array([]),
'H03' : np.array([]),
'H04' : np.array([]),
'H05' : np.array([]),
'H06' : np.array([]),
'H07' : np.array([]),
'H08' : np.array([]),
'H09' : np.array([]),
'H10' : np.array([]),
'H11' : np.array([]),
'H12' : np.array([]),
'H13' : np.array([]),
'H14' : np.array([]),
'H15' : np.array([]),
'H16' : np.array([]),
'H17' : np.array([]),
'H18' : np.array([]),
'H19' : np.array([]),
'H20' : np.array([]),
'f01' : np.array([]),
'f02' : np.array([]),
'f03' : np.array([]),
'f04' : np.array([]),
'f05' : np.array([]),
'f06' : np.array([]),
'f07' : np.array([]),
'f08' : np.array([]),
'f09' : np.array([]),
'f10' : np.array([]),
'f11' : np.array([]),
'f12' : np.array([]),
'f13' : np.array([]),
'f14' : np.array([]),
'f15' : np.array([]),
'f16' : np.array([]),
'f17' : np.array([]),
'f18' : np.array([]),
'f19' : np.array([]),
'f20' : np.array([]),
'A01' : np.array([]),
'A02' : np.array([]),
'A03' : np.array([]),
'A04' : np.array([]),
'A05' : np.array([]),
'A06' : np.array([]),
'A07' : np.array([]),
'A08' : np.array([]),
'A09' : np.array([]),
'A10' : np.array([]),
'A11' : np.array([]),
'A12' : np.array([]),
'A13' : np.array([]),
'A14' : np.array([]),
'A15' : np.array([]),
'A16' : np.array([]),
'A17' : np.array([]),
'A18' : np.array([]),
'A19' : np.array([]),
'A20' : np.array([]),
'b01' : np.array([]),
'b02' : np.array([]),
'b03' : np.array([]),
'b04' : np.array([]),
'b05' : np.array([]),
'b06' : np.array([]),
'b07' : np.array([]),
'b08' : np.array([]),
'b09' : np.array([]),
'b10' : np.array([]),
'b11' : np.array([]),
'b12' : np.array([]),
'b13' : np.array([]),
'b14' : np.array([]),
'b15' : np.array([]),
'b16' : np.array([]),
'b17' : np.array([]),
'b18' : np.array([]),
'b19' : np.array([]),
'b20' : np.array([]),
'C01' : np.array([]),
'C02' : np.array([]),
'C03' : np.array([]),
'C04' : np.array([]),
'C05' : np.array([]),
'C06' : np.array([]),
'C07' : np.array([]),
'C08' : np.array([]),
'C09' : np.array([]),
'C10' : np.array([]),
'C11' : np.array([]),
'C12' : np.array([]),
'C13' : np.array([]),
'C14' : np.array([]),
'C15' : np.array([]),
'C16' : np.array([]),
'C17' : np.array([]),
'C18' : np.array([]),
'C19' : np.array([]),
'D01' : np.array([]),
'D02' : np.array([]),
'D03' : np.array([]),
'D04' : np.array([]),
'D05' : np.array([]),
'D06' : np.array([]),
'D07' : np.array([]),
'D08' : np.array([]),
'D09' : np.array([]),
'D10' : np.array([]),
'D11' : np.array([]),
'D12' : np.array([]),
'D13' : np.array([]),
'D14' : np.array([]),
'D15' : np.array([]),
'D16' : np.array([]),
'D17' : np.array([]),
'D18' : np.array([]),
'D19' : np.array([]),
'D20' : np.array([]),
'c02' : np.array([]),
'c03' : np.array([]),
'c04' : np.array([]),
'c05' : np.array([]),
'c06' : np.array([]),
'c07' : np.array([]),
'c08' : np.array([]),
'c09' : np.array([]),
'c10' : np.array([]),
'c11' : np.array([]),
'c12' : np.array([]),
'c13' : np.array([]),
'c14' : np.array([]),
'c15' : np.array([]),
'c16' : np.array([]),
'c17' : np.array([]),
'c18' : np.array([]),
'c19' : np.array([]),
'c20' : np.array([]),
'minusA_times_x0' : np.array([]),
}
params = {'H01' : np.array([]),
'H02' : np.array([]),
'H03' : np.array([]),
'H04' : np.array([]),
'H05' : np.array([]),
'H06' : np.array([]),
'H07' : np.array([]),
'H08' : np.array([]),
'H09' : np.array([]),
'H10' : np.array([]),
'H11' : np.array([]),
'H12' : np.array([]),
'H13' : np.array([]),
'H14' : np.array([]),
'H15' : np.array([]),
'H16' : np.array([]),
'H17' : np.array([]),
'H18' : np.array([]),
'H19' : np.array([]),
'H20' : np.array([]),
'f01' : np.array([]),
'f02' : np.array([]),
'f03' : np.array([]),
'f04' : np.array([]),
'f05' : np.array([]),
'f06' : np.array([]),
'f07' : np.array([]),
'f08' : np.array([]),
'f09' : np.array([]),
'f10' : np.array([]),
'f11' : np.array([]),
'f12' : np.array([]),
'f13' : np.array([]),
'f14' : np.array([]),
'f15' : np.array([]),
'f16' : np.array([]),
'f17' : np.array([]),
'f18' : np.array([]),
'f19' : np.array([]),
'f20' : np.array([]),
'A01' : np.array([]),
'A02' : np.array([]),
'A03' : np.array([]),
'A04' : np.array([]),
'A05' : np.array([]),
'A06' : np.array([]),
'A07' : np.array([]),
'A08' : np.array([]),
'A09' : np.array([]),
'A10' : np.array([]),
'A11' : np.array([]),
'A12' : np.array([]),
'A13' : np.array([]),
'A14' : np.array([]),
'A15' : np.array([]),
'A16' : np.array([]),
'A17' : np.array([]),
'A18' : np.array([]),
'A19' : np.array([]),
'A20' : np.array([]),
'b01' : np.array([]),
'b02' : np.array([]),
'b03' : np.array([]),
'b04' : np.array([]),
'b05' : np.array([]),
'b06' : np.array([]),
'b07' : np.array([]),
'b08' : np.array([]),
'b09' : np.array([]),
'b10' : np.array([]),
'b11' : np.array([]),
'b12' : np.array([]),
'b13' : np.array([]),
'b14' : np.array([]),
'b15' : np.array([]),
'b16' : np.array([]),
'b17' : np.array([]),
'b18' : np.array([]),
'b19' : np.array([]),
'b20' : np.array([]),
'C01' : np.array([]),
'C02' : np.array([]),
'C03' : np.array([]),
'C04' : np.array([]),
'C05' : np.array([]),
'C06' : np.array([]),
'C07' : np.array([]),
'C08' : np.array([]),
'C09' : np.array([]),
'C10' : np.array([]),
'C11' : np.array([]),
'C12' : np.array([]),
'C13' : np.array([]),
'C14' : np.array([]),
'C15' : np.array([]),
'C16' : np.array([]),
'C17' : np.array([]),
'C18' : np.array([]),
'C19' : np.array([]),
'D01' : np.array([]),
'D02' : np.array([]),
'D03' : np.array([]),
'D04' : np.array([]),
'D05' : np.array([]),
'D06' : np.array([]),
'D07' : np.array([]),
'D08' : np.array([]),
'D09' : np.array([]),
'D10' : np.array([]),
'D11' : np.array([]),
'D12' : np.array([]),
'D13' : np.array([]),
'D14' : np.array([]),
'D15' : np.array([]),
'D16' : np.array([]),
'D17' : np.array([]),
'D18' : np.array([]),
'D19' : np.array([]),
'D20' : np.array([]),
'c02' : np.array([]),
'c03' : np.array([]),
'c04' : np.array([]),
'c05' : np.array([]),
'c06' : np.array([]),
'c07' : np.array([]),
'c08' : np.array([]),
'c09' : np.array([]),
'c10' : np.array([]),
'c11' : np.array([]),
'c12' : np.array([]),
'c13' : np.array([]),
'c14' : np.array([]),
'c15' : np.array([]),
'c16' : np.array([]),
'c17' : np.array([]),
'c18' : np.array([]),
'c19' : np.array([]),
'c20' : np.array([]),
'minusA_times_x0' : np.array([]),
}
mpcc_params_types = {'H01' : np.float64,
'H02' : np.float64,
'H03' : np.float64,
'H04' : np.float64,
'H05' : np.float64,
'H06' : np.float64,
'H07' : np.float64,
'H08' : np.float64,
'H09' : np.float64,
'H10' : np.float64,
'H11' : np.float64,
'H12' : np.float64,
'H13' : np.float64,
'H14' : np.float64,
'H15' : np.float64,
'H16' : np.float64,
'H17' : np.float64,
'H18' : np.float64,
'H19' : np.float64,
'H20' : np.float64,
'f01' : np.float64,
'f02' : np.float64,
'f03' : np.float64,
'f04' : np.float64,
'f05' : np.float64,
'f06' : np.float64,
'f07' : np.float64,
'f08' : np.float64,
'f09' : np.float64,
'f10' : np.float64,
'f11' : np.float64,
'f12' : np.float64,
'f13' : np.float64,
'f14' : np.float64,
'f15' : np.float64,
'f16' : np.float64,
'f17' : np.float64,
'f18' : np.float64,
'f19' : np.float64,
'f20' : np.float64,
'A01' : np.float64,
'A02' : np.float64,
'A03' : np.float64,
'A04' : np.float64,
'A05' : np.float64,
'A06' : np.float64,
'A07' : np.float64,
'A08' : np.float64,
'A09' : np.float64,
'A10' : np.float64,
'A11' : np.float64,
'A12' : np.float64,
'A13' : np.float64,
'A14' : np.float64,
'A15' : np.float64,
'A16' : np.float64,
'A17' : np.float64,
'A18' : np.float64,
'A19' : np.float64,
'A20' : np.float64,
'b01' : np.float64,
'b02' : np.float64,
'b03' : np.float64,
'b04' : np.float64,
'b05' : np.float64,
'b06' : np.float64,
'b07' : np.float64,
'b08' : np.float64,
'b09' : np.float64,
'b10' : np.float64,
'b11' : np.float64,
'b12' : np.float64,
'b13' : np.float64,
'b14' : np.float64,
'b15' : np.float64,
'b16' : np.float64,
'b17' : np.float64,
'b18' : np.float64,
'b19' : np.float64,
'b20' : np.float64,
'C01' : np.float64,
'C02' : np.float64,
'C03' : np.float64,
'C04' : np.float64,
'C05' : np.float64,
'C06' : np.float64,
'C07' : np.float64,
'C08' : np.float64,
'C09' : np.float64,
'C10' : np.float64,
'C11' : np.float64,
'C12' : np.float64,
'C13' : np.float64,
'C14' : np.float64,
'C15' : np.float64,
'C16' : np.float64,
'C17' : np.float64,
'C18' : np.float64,
'C19' : np.float64,
'D01' : np.float64,
'D02' : np.float64,
'D03' : np.float64,
'D04' : np.float64,
'D05' : np.float64,
'D06' : np.float64,
'D07' : np.float64,
'D08' : np.float64,
'D09' : np.float64,
'D10' : np.float64,
'D11' : np.float64,
'D12' : np.float64,
'D13' : np.float64,
'D14' : np.float64,
'D15' : np.float64,
'D16' : np.float64,
'D17' : np.float64,
'D18' : np.float64,
'D19' : np.float64,
'D20' : np.float64,
'c02' : np.float64,
'c03' : np.float64,
'c04' : np.float64,
'c05' : np.float64,
'c06' : np.float64,
'c07' : np.float64,
'c08' : np.float64,
'c09' : np.float64,
'c10' : np.float64,
'c11' : np.float64,
'c12' : np.float64,
'c13' : np.float64,
'c14' : np.float64,
'c15' : np.float64,
'c16' : np.float64,
'c17' : np.float64,
'c18' : np.float64,
'c19' : np.float64,
'c20' : np.float64,
'minusA_times_x0' : np.float64,
}

class mpcc_outputs_ctypes(ctypes.Structure):
#    @classmethod
#    def from_param(self):
#        return self
    _fields_ = [('u0', ctypes.c_double * 260),
]

mpcc_outputs = {'u0' : np.array([]),
}


class mpcc_info(ctypes.Structure):
#    @classmethod
#    def from_param(self):
#        return self
    _fields_ = [('it', ctypes.c_int32),
('it2opt', ctypes.c_int32),
('res_eq', ctypes.c_double),
('res_ineq', ctypes.c_double),
('pobj', ctypes.c_double),
('dobj', ctypes.c_double),
('dgap', ctypes.c_double),
('rdgap', ctypes.c_double),
('gradient_lag_norm', ctypes.c_double),
('mu', ctypes.c_double),
('mu_aff', ctypes.c_double),
('sigma', ctypes.c_double),
('lsit_aff', ctypes.c_int32),
('lsit_cc', ctypes.c_int32),
('step_aff', ctypes.c_double),
('step_cc', ctypes.c_double),
('solvetime', ctypes.c_double)
]

class FILE(ctypes.Structure):
        pass
if sys.version_info.major == 2:
    PyFile_AsFile = ctypes.pythonapi.PyFile_AsFile # problem here with python 3 http://stackoverflow.com/questions/16130268/python-3-replacement-for-pyfile-asfile
    PyFile_AsFile.argtypes = [ctypes.py_object]
    PyFile_AsFile.restype = ctypes.POINTER(FILE)

# determine data types for solver function prototype 
csolver.argtypes = ( ctypes.POINTER(mpcc_params_ctypes), ctypes.POINTER(mpcc_outputs_ctypes), ctypes.POINTER(mpcc_info), ctypes.POINTER(FILE))
csolver.restype = ctypes.c_int

def mpcc_solve(params_arg):
    '''
a Python wrapper for a fast solver generated by FORCESPRO v4.2.1

   OUTPUT = mpcc_py.mpcc_solve(PARAMS) solves a multistage problem
   subject to the parameters supplied in the following dictionary:
       PARAMS['H01'] - matrix of size [13 x 13]
       PARAMS['H02'] - matrix of size [13 x 13]
       PARAMS['H03'] - matrix of size [13 x 13]
       PARAMS['H04'] - matrix of size [13 x 13]
       PARAMS['H05'] - matrix of size [13 x 13]
       PARAMS['H06'] - matrix of size [13 x 13]
       PARAMS['H07'] - matrix of size [13 x 13]
       PARAMS['H08'] - matrix of size [13 x 13]
       PARAMS['H09'] - matrix of size [13 x 13]
       PARAMS['H10'] - matrix of size [13 x 13]
       PARAMS['H11'] - matrix of size [13 x 13]
       PARAMS['H12'] - matrix of size [13 x 13]
       PARAMS['H13'] - matrix of size [13 x 13]
       PARAMS['H14'] - matrix of size [13 x 13]
       PARAMS['H15'] - matrix of size [13 x 13]
       PARAMS['H16'] - matrix of size [13 x 13]
       PARAMS['H17'] - matrix of size [13 x 13]
       PARAMS['H18'] - matrix of size [13 x 13]
       PARAMS['H19'] - matrix of size [13 x 13]
       PARAMS['H20'] - matrix of size [13 x 13]
       PARAMS['f01'] - column vector of length 13
       PARAMS['f02'] - column vector of length 13
       PARAMS['f03'] - column vector of length 13
       PARAMS['f04'] - column vector of length 13
       PARAMS['f05'] - column vector of length 13
       PARAMS['f06'] - column vector of length 13
       PARAMS['f07'] - column vector of length 13
       PARAMS['f08'] - column vector of length 13
       PARAMS['f09'] - column vector of length 13
       PARAMS['f10'] - column vector of length 13
       PARAMS['f11'] - column vector of length 13
       PARAMS['f12'] - column vector of length 13
       PARAMS['f13'] - column vector of length 13
       PARAMS['f14'] - column vector of length 13
       PARAMS['f15'] - column vector of length 13
       PARAMS['f16'] - column vector of length 13
       PARAMS['f17'] - column vector of length 13
       PARAMS['f18'] - column vector of length 13
       PARAMS['f19'] - column vector of length 13
       PARAMS['f20'] - column vector of length 13
       PARAMS['A01'] - matrix of size [2 x 13]
       PARAMS['A02'] - matrix of size [2 x 13]
       PARAMS['A03'] - matrix of size [2 x 13]
       PARAMS['A04'] - matrix of size [2 x 13]
       PARAMS['A05'] - matrix of size [2 x 13]
       PARAMS['A06'] - matrix of size [2 x 13]
       PARAMS['A07'] - matrix of size [2 x 13]
       PARAMS['A08'] - matrix of size [2 x 13]
       PARAMS['A09'] - matrix of size [2 x 13]
       PARAMS['A10'] - matrix of size [2 x 13]
       PARAMS['A11'] - matrix of size [2 x 13]
       PARAMS['A12'] - matrix of size [2 x 13]
       PARAMS['A13'] - matrix of size [2 x 13]
       PARAMS['A14'] - matrix of size [2 x 13]
       PARAMS['A15'] - matrix of size [2 x 13]
       PARAMS['A16'] - matrix of size [2 x 13]
       PARAMS['A17'] - matrix of size [2 x 13]
       PARAMS['A18'] - matrix of size [2 x 13]
       PARAMS['A19'] - matrix of size [2 x 13]
       PARAMS['A20'] - matrix of size [2 x 13]
       PARAMS['b01'] - column vector of length 2
       PARAMS['b02'] - column vector of length 2
       PARAMS['b03'] - column vector of length 2
       PARAMS['b04'] - column vector of length 2
       PARAMS['b05'] - column vector of length 2
       PARAMS['b06'] - column vector of length 2
       PARAMS['b07'] - column vector of length 2
       PARAMS['b08'] - column vector of length 2
       PARAMS['b09'] - column vector of length 2
       PARAMS['b10'] - column vector of length 2
       PARAMS['b11'] - column vector of length 2
       PARAMS['b12'] - column vector of length 2
       PARAMS['b13'] - column vector of length 2
       PARAMS['b14'] - column vector of length 2
       PARAMS['b15'] - column vector of length 2
       PARAMS['b16'] - column vector of length 2
       PARAMS['b17'] - column vector of length 2
       PARAMS['b18'] - column vector of length 2
       PARAMS['b19'] - column vector of length 2
       PARAMS['b20'] - column vector of length 2
       PARAMS['C01'] - matrix of size [10 x 13]
       PARAMS['C02'] - matrix of size [10 x 13]
       PARAMS['C03'] - matrix of size [10 x 13]
       PARAMS['C04'] - matrix of size [10 x 13]
       PARAMS['C05'] - matrix of size [10 x 13]
       PARAMS['C06'] - matrix of size [10 x 13]
       PARAMS['C07'] - matrix of size [10 x 13]
       PARAMS['C08'] - matrix of size [10 x 13]
       PARAMS['C09'] - matrix of size [10 x 13]
       PARAMS['C10'] - matrix of size [10 x 13]
       PARAMS['C11'] - matrix of size [10 x 13]
       PARAMS['C12'] - matrix of size [10 x 13]
       PARAMS['C13'] - matrix of size [10 x 13]
       PARAMS['C14'] - matrix of size [10 x 13]
       PARAMS['C15'] - matrix of size [10 x 13]
       PARAMS['C16'] - matrix of size [10 x 13]
       PARAMS['C17'] - matrix of size [10 x 13]
       PARAMS['C18'] - matrix of size [10 x 13]
       PARAMS['C19'] - matrix of size [10 x 13]
       PARAMS['D01'] - matrix of size [10 x 13]
       PARAMS['D02'] - matrix of size [10 x 13]
       PARAMS['D03'] - matrix of size [10 x 13]
       PARAMS['D04'] - matrix of size [10 x 13]
       PARAMS['D05'] - matrix of size [10 x 13]
       PARAMS['D06'] - matrix of size [10 x 13]
       PARAMS['D07'] - matrix of size [10 x 13]
       PARAMS['D08'] - matrix of size [10 x 13]
       PARAMS['D09'] - matrix of size [10 x 13]
       PARAMS['D10'] - matrix of size [10 x 13]
       PARAMS['D11'] - matrix of size [10 x 13]
       PARAMS['D12'] - matrix of size [10 x 13]
       PARAMS['D13'] - matrix of size [10 x 13]
       PARAMS['D14'] - matrix of size [10 x 13]
       PARAMS['D15'] - matrix of size [10 x 13]
       PARAMS['D16'] - matrix of size [10 x 13]
       PARAMS['D17'] - matrix of size [10 x 13]
       PARAMS['D18'] - matrix of size [10 x 13]
       PARAMS['D19'] - matrix of size [10 x 13]
       PARAMS['D20'] - matrix of size [10 x 13]
       PARAMS['c02'] - column vector of length 10
       PARAMS['c03'] - column vector of length 10
       PARAMS['c04'] - column vector of length 10
       PARAMS['c05'] - column vector of length 10
       PARAMS['c06'] - column vector of length 10
       PARAMS['c07'] - column vector of length 10
       PARAMS['c08'] - column vector of length 10
       PARAMS['c09'] - column vector of length 10
       PARAMS['c10'] - column vector of length 10
       PARAMS['c11'] - column vector of length 10
       PARAMS['c12'] - column vector of length 10
       PARAMS['c13'] - column vector of length 10
       PARAMS['c14'] - column vector of length 10
       PARAMS['c15'] - column vector of length 10
       PARAMS['c16'] - column vector of length 10
       PARAMS['c17'] - column vector of length 10
       PARAMS['c18'] - column vector of length 10
       PARAMS['c19'] - column vector of length 10
       PARAMS['c20'] - column vector of length 10
       PARAMS['minusA_times_x0'] - column vector of length 10

   OUTPUT returns the values of the last iteration of the solver where
       OUTPUT['u0'] - column vector of size 260

   [OUTPUT, EXITFLAG] = mpcc_py.mpcc_solve(PARAMS) returns additionally
   the integer EXITFLAG indicating the state of the solution with 
       1 - Optimal solution has been found (subject to desired accuracy)
       2 - (only branch-and-bound) A feasible point has been identified for which the objective value is no more than codeoptions.mip.mipgap*100 per cent worse than the global optimum 
       0 - Timeout - maximum number of iterations reached
      -1 - (only branch-and-bound) Infeasible problem (problems solving the root relaxation to the desired accuracy)
      -2 - (only branch-and-bound) Out of memory - cannot fit branch and bound nodes into pre-allocated memory.
      -6 - NaN or INF occured during evaluation of functions and derivatives. Please check your initial guess.
      -7 - Method could not progress. Problem may be infeasible. Run FORCESdiagnostics on your problem to check for most common errors in the formulation.
     -10 - The convex solver could not proceed due to an internal error
    -100 - License error

   [OUTPUT, EXITFLAG, INFO] = mpcc_py.mpcc_solve(PARAMS) returns 
   additional information about the last iterate:
       INFO.it        - number of iterations that lead to this result
       INFO.it2opt    - number of convex solves
       INFO.res_eq    - max. equality constraint residual
       INFO.res_ineq  - max. inequality constraint residual
       INFO.pobj      - primal objective
       INFO.dobj      - dual objective
       INFO.dgap      - duality gap := pobj - dobj
       INFO.rdgap     - relative duality gap := |dgap / pobj|
       INFO.gradient_lag_norm - infinity norm of gradient of Lagrangian
       INFO.mu        - duality measure
       INFO.sigma     - centering parameter
       INFO.lsit_aff  - iterations of affine line search
       INFO.lsit_cc   - iterations of line search (combined direction)
       INFO.step_aff  - step size (affine direction)
       INFO.step_cc   - step size (centering direction)
       INFO.solvetime - Time needed for solve (wall clock time)

 See also COPYING

    '''
    global _lib

    # convert parameters
    params_py = mpcc_params_ctypes()
    for par in params_arg:
        try:
            #setattr(params_py, par, npct.as_ctypes(np.reshape(params_arg[par],np.size(params_arg[par]),order='A')))
            if isinstance(getattr(params_py, par), ctypes.Array):
                params_arg[par] = np.require(params_arg[par], dtype=mpcc_params_types[par], requirements='F')
                setattr(params_py, par, npct.as_ctypes(np.reshape(params_arg[par],np.size(params_arg[par]),order='F')))
            else:
                setattr(params_py, par, params_arg[par])
        except:
            raise ValueError('Parameter ' + par + ' does not have the appropriate dimensions or data type. Please use numpy arrays for parameters.')
    
    outputs_py = mpcc_outputs_ctypes()
    info_py = mpcc_info()
    if sys.version_info.major == 2:
        if sys.platform.startswith('win'):
            fp = None # if set to none, the solver prints to stdout by default - necessary because we have an access violation otherwise under windows
        else:
            #fp = open('stdout_temp.txt','w')
            fp = sys.stdout
        try:
            PyFile_AsFile.restype = ctypes.POINTER(FILE)
            exitflag = _lib.mpcc_solve( ctypes.byref(params_py), ctypes.byref(outputs_py), ctypes.byref(info_py), PyFile_AsFile(fp)  )
            #fp = open('stdout_temp.txt','r')
            #print (fp.read())
            #fp.close()
        except:
            #print 'Problem with solver'
            raise
    elif sys.version_info.major == 3:
        if sys.platform.startswith('win'):
            libc = ctypes.cdll.msvcrt
        elif sys.platform.startswith('darwin'):
            libc = ctypes.CDLL('libc.dylib')
        else:
            libc = ctypes.CDLL('libc.so.6')       # Open libc
        cfopen = getattr(libc,'fopen')        # Get its fopen
        cfopen.restype = ctypes.POINTER(FILE) # Yes, fopen gives a file pointer
        cfopen.argtypes = [ctypes.c_char_p, ctypes.c_char_p] # Yes, fopen gives a file pointer 
        fp = cfopen('stdout_temp.txt'.encode('utf-8'),'w'.encode('utf-8'))    # Use that fopen 

        try:
            if sys.platform.startswith('win'):
                exitflag = _lib.mpcc_solve( ctypes.byref(params_py), ctypes.byref(outputs_py), ctypes.byref(info_py), None )
            else:
                exitflag = _lib.mpcc_solve( ctypes.byref(params_py), ctypes.byref(outputs_py), ctypes.byref(info_py), fp )
            libc.fclose(fp)
            fptemp = open('stdout_temp.txt','r')
            print (fptemp.read())
            fptemp.close()            
        except:
            #print 'Problem with solver'
            raise

    # convert outputs
    for out in mpcc_outputs:
        mpcc_outputs[out] = npct.as_array(getattr(outputs_py,out))

    return mpcc_outputs,int(exitflag),info_py

solve = mpcc_solve


