# metadata
run_name: 'map_wide'
# characteristic number for map
perf_num: 1

# map paths
map_path: './IMS_map'
map_ext: '.png'

# starting pose for map
sx: 0.00000
sy: 0
# sy: -0.8243256
# stheta: 1.37079632679
stheta: -1.56

# raceline path and indices
wpt_path: './IMS_map_waypoints.csv'
wpt_delim: ','
wpt_rowskip: 0
wpt_xind: 0
wpt_yind: 1
wpt_width_right: 2
wpt_width_left: 3

# varied params bound
# physical params
mass_min: 3.0
mass_max: 4.0
lf_min: 0.147
lf_max: 0.170
# controller params
tlad_min: 0.2
tlad_max: 5.
vgain_min: 0.5
vgain_max: 1.5

# computation budget (can think of it as gen_num times pop_size)
popsize: 100
budget: 1000

# optimization method
optim_method: 'CMA'

# seed
seed: 12345