% mpcc - a fast solver generated by FORCESPRO v4.2.1
%
%   OUTPUT = mpcc(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.H01 - matrix of size [13 x 13]
%       PARAMS.H02 - matrix of size [13 x 13]
%       PARAMS.H03 - matrix of size [13 x 13]
%       PARAMS.H04 - matrix of size [13 x 13]
%       PARAMS.H05 - matrix of size [13 x 13]
%       PARAMS.H06 - matrix of size [13 x 13]
%       PARAMS.H07 - matrix of size [13 x 13]
%       PARAMS.H08 - matrix of size [13 x 13]
%       PARAMS.H09 - matrix of size [13 x 13]
%       PARAMS.H10 - matrix of size [13 x 13]
%       PARAMS.H11 - matrix of size [13 x 13]
%       PARAMS.H12 - matrix of size [13 x 13]
%       PARAMS.H13 - matrix of size [13 x 13]
%       PARAMS.H14 - matrix of size [13 x 13]
%       PARAMS.H15 - matrix of size [13 x 13]
%       PARAMS.H16 - matrix of size [13 x 13]
%       PARAMS.H17 - matrix of size [13 x 13]
%       PARAMS.H18 - matrix of size [13 x 13]
%       PARAMS.H19 - matrix of size [13 x 13]
%       PARAMS.H20 - matrix of size [13 x 13]
%       PARAMS.f01 - column vector of length 13
%       PARAMS.f02 - column vector of length 13
%       PARAMS.f03 - column vector of length 13
%       PARAMS.f04 - column vector of length 13
%       PARAMS.f05 - column vector of length 13
%       PARAMS.f06 - column vector of length 13
%       PARAMS.f07 - column vector of length 13
%       PARAMS.f08 - column vector of length 13
%       PARAMS.f09 - column vector of length 13
%       PARAMS.f10 - column vector of length 13
%       PARAMS.f11 - column vector of length 13
%       PARAMS.f12 - column vector of length 13
%       PARAMS.f13 - column vector of length 13
%       PARAMS.f14 - column vector of length 13
%       PARAMS.f15 - column vector of length 13
%       PARAMS.f16 - column vector of length 13
%       PARAMS.f17 - column vector of length 13
%       PARAMS.f18 - column vector of length 13
%       PARAMS.f19 - column vector of length 13
%       PARAMS.f20 - column vector of length 13
%       PARAMS.A01 - matrix of size [2 x 13]
%       PARAMS.A02 - matrix of size [2 x 13]
%       PARAMS.A03 - matrix of size [2 x 13]
%       PARAMS.A04 - matrix of size [2 x 13]
%       PARAMS.A05 - matrix of size [2 x 13]
%       PARAMS.A06 - matrix of size [2 x 13]
%       PARAMS.A07 - matrix of size [2 x 13]
%       PARAMS.A08 - matrix of size [2 x 13]
%       PARAMS.A09 - matrix of size [2 x 13]
%       PARAMS.A10 - matrix of size [2 x 13]
%       PARAMS.A11 - matrix of size [2 x 13]
%       PARAMS.A12 - matrix of size [2 x 13]
%       PARAMS.A13 - matrix of size [2 x 13]
%       PARAMS.A14 - matrix of size [2 x 13]
%       PARAMS.A15 - matrix of size [2 x 13]
%       PARAMS.A16 - matrix of size [2 x 13]
%       PARAMS.A17 - matrix of size [2 x 13]
%       PARAMS.A18 - matrix of size [2 x 13]
%       PARAMS.A19 - matrix of size [2 x 13]
%       PARAMS.A20 - matrix of size [2 x 13]
%       PARAMS.b01 - column vector of length 2
%       PARAMS.b02 - column vector of length 2
%       PARAMS.b03 - column vector of length 2
%       PARAMS.b04 - column vector of length 2
%       PARAMS.b05 - column vector of length 2
%       PARAMS.b06 - column vector of length 2
%       PARAMS.b07 - column vector of length 2
%       PARAMS.b08 - column vector of length 2
%       PARAMS.b09 - column vector of length 2
%       PARAMS.b10 - column vector of length 2
%       PARAMS.b11 - column vector of length 2
%       PARAMS.b12 - column vector of length 2
%       PARAMS.b13 - column vector of length 2
%       PARAMS.b14 - column vector of length 2
%       PARAMS.b15 - column vector of length 2
%       PARAMS.b16 - column vector of length 2
%       PARAMS.b17 - column vector of length 2
%       PARAMS.b18 - column vector of length 2
%       PARAMS.b19 - column vector of length 2
%       PARAMS.b20 - column vector of length 2
%       PARAMS.C01 - matrix of size [10 x 13]
%       PARAMS.C02 - matrix of size [10 x 13]
%       PARAMS.C03 - matrix of size [10 x 13]
%       PARAMS.C04 - matrix of size [10 x 13]
%       PARAMS.C05 - matrix of size [10 x 13]
%       PARAMS.C06 - matrix of size [10 x 13]
%       PARAMS.C07 - matrix of size [10 x 13]
%       PARAMS.C08 - matrix of size [10 x 13]
%       PARAMS.C09 - matrix of size [10 x 13]
%       PARAMS.C10 - matrix of size [10 x 13]
%       PARAMS.C11 - matrix of size [10 x 13]
%       PARAMS.C12 - matrix of size [10 x 13]
%       PARAMS.C13 - matrix of size [10 x 13]
%       PARAMS.C14 - matrix of size [10 x 13]
%       PARAMS.C15 - matrix of size [10 x 13]
%       PARAMS.C16 - matrix of size [10 x 13]
%       PARAMS.C17 - matrix of size [10 x 13]
%       PARAMS.C18 - matrix of size [10 x 13]
%       PARAMS.C19 - matrix of size [10 x 13]
%       PARAMS.D01 - matrix of size [10 x 13]
%       PARAMS.D02 - matrix of size [10 x 13]
%       PARAMS.D03 - matrix of size [10 x 13]
%       PARAMS.D04 - matrix of size [10 x 13]
%       PARAMS.D05 - matrix of size [10 x 13]
%       PARAMS.D06 - matrix of size [10 x 13]
%       PARAMS.D07 - matrix of size [10 x 13]
%       PARAMS.D08 - matrix of size [10 x 13]
%       PARAMS.D09 - matrix of size [10 x 13]
%       PARAMS.D10 - matrix of size [10 x 13]
%       PARAMS.D11 - matrix of size [10 x 13]
%       PARAMS.D12 - matrix of size [10 x 13]
%       PARAMS.D13 - matrix of size [10 x 13]
%       PARAMS.D14 - matrix of size [10 x 13]
%       PARAMS.D15 - matrix of size [10 x 13]
%       PARAMS.D16 - matrix of size [10 x 13]
%       PARAMS.D17 - matrix of size [10 x 13]
%       PARAMS.D18 - matrix of size [10 x 13]
%       PARAMS.D19 - matrix of size [10 x 13]
%       PARAMS.D20 - matrix of size [10 x 13]
%       PARAMS.c02 - column vector of length 10
%       PARAMS.c03 - column vector of length 10
%       PARAMS.c04 - column vector of length 10
%       PARAMS.c05 - column vector of length 10
%       PARAMS.c06 - column vector of length 10
%       PARAMS.c07 - column vector of length 10
%       PARAMS.c08 - column vector of length 10
%       PARAMS.c09 - column vector of length 10
%       PARAMS.c10 - column vector of length 10
%       PARAMS.c11 - column vector of length 10
%       PARAMS.c12 - column vector of length 10
%       PARAMS.c13 - column vector of length 10
%       PARAMS.c14 - column vector of length 10
%       PARAMS.c15 - column vector of length 10
%       PARAMS.c16 - column vector of length 10
%       PARAMS.c17 - column vector of length 10
%       PARAMS.c18 - column vector of length 10
%       PARAMS.c19 - column vector of length 10
%       PARAMS.c20 - column vector of length 10
%       PARAMS.minusA_times_x0 - column vector of length 10
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.u0 - column vector of size 260
%
%   [OUTPUT, EXITFLAG] = mpcc(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - OPTIMAL solution has been found (subject to desired accuracy)
%       0 - Timeout - maximum number of iterations reached
%      -7 - Method could not progress. Problem may be infeasible. Run FORCESdiagnostics on your problem to check for most common errors in the formulation.
%    -100 - License error
%
%   [OUTPUT, EXITFLAG, INFO] = mpcc(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.pobj      - primal objective
%       INFO.dobj      - dual objective
%       INFO.dgap      - duality gap := pobj - dobj
%       INFO.rdgap     - relative duality gap := |dgap / pobj|
%       INFO.mu        - duality measure
%       INFO.sigma     - centering parameter
%       INFO.lsit_aff  - iterations of affine line search
%       INFO.lsit_cc   - iterations of line search (combined direction)
%       INFO.step_aff  - step size (affine direction)
%       INFO.step_cc   - step size (centering direction)
%       INFO.solvetime - Time needed for solve (wall clock time)
%
% See also COPYING
