% mpcc - a fast solver generated by FORCESPRO v4.2.0
%
%   OUTPUT = mpcc(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.H01 - matrix of size [14 x 14]
%       PARAMS.H02 - matrix of size [14 x 14]
%       PARAMS.H03 - matrix of size [14 x 14]
%       PARAMS.H04 - matrix of size [14 x 14]
%       PARAMS.H05 - matrix of size [14 x 14]
%       PARAMS.H06 - matrix of size [14 x 14]
%       PARAMS.H07 - matrix of size [14 x 14]
%       PARAMS.H08 - matrix of size [14 x 14]
%       PARAMS.H09 - matrix of size [14 x 14]
%       PARAMS.H10 - matrix of size [14 x 14]
%       PARAMS.H11 - matrix of size [14 x 14]
%       PARAMS.H12 - matrix of size [14 x 14]
%       PARAMS.H13 - matrix of size [14 x 14]
%       PARAMS.H14 - matrix of size [14 x 14]
%       PARAMS.H15 - matrix of size [14 x 14]
%       PARAMS.H16 - matrix of size [14 x 14]
%       PARAMS.H17 - matrix of size [14 x 14]
%       PARAMS.H18 - matrix of size [14 x 14]
%       PARAMS.H19 - matrix of size [14 x 14]
%       PARAMS.H20 - matrix of size [14 x 14]
%       PARAMS.H21 - matrix of size [14 x 14]
%       PARAMS.H22 - matrix of size [14 x 14]
%       PARAMS.H23 - matrix of size [14 x 14]
%       PARAMS.H24 - matrix of size [14 x 14]
%       PARAMS.H25 - matrix of size [14 x 14]
%       PARAMS.H26 - matrix of size [14 x 14]
%       PARAMS.H27 - matrix of size [14 x 14]
%       PARAMS.H28 - matrix of size [14 x 14]
%       PARAMS.H29 - matrix of size [14 x 14]
%       PARAMS.H30 - matrix of size [14 x 14]
%       PARAMS.H31 - matrix of size [14 x 14]
%       PARAMS.H32 - matrix of size [14 x 14]
%       PARAMS.H33 - matrix of size [14 x 14]
%       PARAMS.H34 - matrix of size [14 x 14]
%       PARAMS.H35 - matrix of size [14 x 14]
%       PARAMS.H36 - matrix of size [14 x 14]
%       PARAMS.H37 - matrix of size [14 x 14]
%       PARAMS.H38 - matrix of size [14 x 14]
%       PARAMS.H39 - matrix of size [14 x 14]
%       PARAMS.H40 - matrix of size [14 x 14]
%       PARAMS.H41 - matrix of size [14 x 14]
%       PARAMS.H42 - matrix of size [14 x 14]
%       PARAMS.H43 - matrix of size [14 x 14]
%       PARAMS.H44 - matrix of size [14 x 14]
%       PARAMS.H45 - matrix of size [14 x 14]
%       PARAMS.H46 - matrix of size [14 x 14]
%       PARAMS.H47 - matrix of size [14 x 14]
%       PARAMS.H48 - matrix of size [14 x 14]
%       PARAMS.H49 - matrix of size [14 x 14]
%       PARAMS.H50 - matrix of size [14 x 14]
%       PARAMS.f01 - column vector of length 14
%       PARAMS.f02 - column vector of length 14
%       PARAMS.f03 - column vector of length 14
%       PARAMS.f04 - column vector of length 14
%       PARAMS.f05 - column vector of length 14
%       PARAMS.f06 - column vector of length 14
%       PARAMS.f07 - column vector of length 14
%       PARAMS.f08 - column vector of length 14
%       PARAMS.f09 - column vector of length 14
%       PARAMS.f10 - column vector of length 14
%       PARAMS.f11 - column vector of length 14
%       PARAMS.f12 - column vector of length 14
%       PARAMS.f13 - column vector of length 14
%       PARAMS.f14 - column vector of length 14
%       PARAMS.f15 - column vector of length 14
%       PARAMS.f16 - column vector of length 14
%       PARAMS.f17 - column vector of length 14
%       PARAMS.f18 - column vector of length 14
%       PARAMS.f19 - column vector of length 14
%       PARAMS.f20 - column vector of length 14
%       PARAMS.f21 - column vector of length 14
%       PARAMS.f22 - column vector of length 14
%       PARAMS.f23 - column vector of length 14
%       PARAMS.f24 - column vector of length 14
%       PARAMS.f25 - column vector of length 14
%       PARAMS.f26 - column vector of length 14
%       PARAMS.f27 - column vector of length 14
%       PARAMS.f28 - column vector of length 14
%       PARAMS.f29 - column vector of length 14
%       PARAMS.f30 - column vector of length 14
%       PARAMS.f31 - column vector of length 14
%       PARAMS.f32 - column vector of length 14
%       PARAMS.f33 - column vector of length 14
%       PARAMS.f34 - column vector of length 14
%       PARAMS.f35 - column vector of length 14
%       PARAMS.f36 - column vector of length 14
%       PARAMS.f37 - column vector of length 14
%       PARAMS.f38 - column vector of length 14
%       PARAMS.f39 - column vector of length 14
%       PARAMS.f40 - column vector of length 14
%       PARAMS.f41 - column vector of length 14
%       PARAMS.f42 - column vector of length 14
%       PARAMS.f43 - column vector of length 14
%       PARAMS.f44 - column vector of length 14
%       PARAMS.f45 - column vector of length 14
%       PARAMS.f46 - column vector of length 14
%       PARAMS.f47 - column vector of length 14
%       PARAMS.f48 - column vector of length 14
%       PARAMS.f49 - column vector of length 14
%       PARAMS.f50 - column vector of length 14
%       PARAMS.A01 - matrix of size [2 x 14]
%       PARAMS.A02 - matrix of size [2 x 14]
%       PARAMS.A03 - matrix of size [2 x 14]
%       PARAMS.A04 - matrix of size [2 x 14]
%       PARAMS.A05 - matrix of size [2 x 14]
%       PARAMS.A06 - matrix of size [2 x 14]
%       PARAMS.A07 - matrix of size [2 x 14]
%       PARAMS.A08 - matrix of size [2 x 14]
%       PARAMS.A09 - matrix of size [2 x 14]
%       PARAMS.A10 - matrix of size [2 x 14]
%       PARAMS.A11 - matrix of size [2 x 14]
%       PARAMS.A12 - matrix of size [2 x 14]
%       PARAMS.A13 - matrix of size [2 x 14]
%       PARAMS.A14 - matrix of size [2 x 14]
%       PARAMS.A15 - matrix of size [2 x 14]
%       PARAMS.A16 - matrix of size [2 x 14]
%       PARAMS.A17 - matrix of size [2 x 14]
%       PARAMS.A18 - matrix of size [2 x 14]
%       PARAMS.A19 - matrix of size [2 x 14]
%       PARAMS.A20 - matrix of size [2 x 14]
%       PARAMS.A21 - matrix of size [2 x 14]
%       PARAMS.A22 - matrix of size [2 x 14]
%       PARAMS.A23 - matrix of size [2 x 14]
%       PARAMS.A24 - matrix of size [2 x 14]
%       PARAMS.A25 - matrix of size [2 x 14]
%       PARAMS.A26 - matrix of size [2 x 14]
%       PARAMS.A27 - matrix of size [2 x 14]
%       PARAMS.A28 - matrix of size [2 x 14]
%       PARAMS.A29 - matrix of size [2 x 14]
%       PARAMS.A30 - matrix of size [2 x 14]
%       PARAMS.A31 - matrix of size [2 x 14]
%       PARAMS.A32 - matrix of size [2 x 14]
%       PARAMS.A33 - matrix of size [2 x 14]
%       PARAMS.A34 - matrix of size [2 x 14]
%       PARAMS.A35 - matrix of size [2 x 14]
%       PARAMS.A36 - matrix of size [2 x 14]
%       PARAMS.A37 - matrix of size [2 x 14]
%       PARAMS.A38 - matrix of size [2 x 14]
%       PARAMS.A39 - matrix of size [2 x 14]
%       PARAMS.A40 - matrix of size [2 x 14]
%       PARAMS.A41 - matrix of size [2 x 14]
%       PARAMS.A42 - matrix of size [2 x 14]
%       PARAMS.A43 - matrix of size [2 x 14]
%       PARAMS.A44 - matrix of size [2 x 14]
%       PARAMS.A45 - matrix of size [2 x 14]
%       PARAMS.A46 - matrix of size [2 x 14]
%       PARAMS.A47 - matrix of size [2 x 14]
%       PARAMS.A48 - matrix of size [2 x 14]
%       PARAMS.A49 - matrix of size [2 x 14]
%       PARAMS.A50 - matrix of size [2 x 14]
%       PARAMS.b01 - column vector of length 2
%       PARAMS.b02 - column vector of length 2
%       PARAMS.b03 - column vector of length 2
%       PARAMS.b04 - column vector of length 2
%       PARAMS.b05 - column vector of length 2
%       PARAMS.b06 - column vector of length 2
%       PARAMS.b07 - column vector of length 2
%       PARAMS.b08 - column vector of length 2
%       PARAMS.b09 - column vector of length 2
%       PARAMS.b10 - column vector of length 2
%       PARAMS.b11 - column vector of length 2
%       PARAMS.b12 - column vector of length 2
%       PARAMS.b13 - column vector of length 2
%       PARAMS.b14 - column vector of length 2
%       PARAMS.b15 - column vector of length 2
%       PARAMS.b16 - column vector of length 2
%       PARAMS.b17 - column vector of length 2
%       PARAMS.b18 - column vector of length 2
%       PARAMS.b19 - column vector of length 2
%       PARAMS.b20 - column vector of length 2
%       PARAMS.b21 - column vector of length 2
%       PARAMS.b22 - column vector of length 2
%       PARAMS.b23 - column vector of length 2
%       PARAMS.b24 - column vector of length 2
%       PARAMS.b25 - column vector of length 2
%       PARAMS.b26 - column vector of length 2
%       PARAMS.b27 - column vector of length 2
%       PARAMS.b28 - column vector of length 2
%       PARAMS.b29 - column vector of length 2
%       PARAMS.b30 - column vector of length 2
%       PARAMS.b31 - column vector of length 2
%       PARAMS.b32 - column vector of length 2
%       PARAMS.b33 - column vector of length 2
%       PARAMS.b34 - column vector of length 2
%       PARAMS.b35 - column vector of length 2
%       PARAMS.b36 - column vector of length 2
%       PARAMS.b37 - column vector of length 2
%       PARAMS.b38 - column vector of length 2
%       PARAMS.b39 - column vector of length 2
%       PARAMS.b40 - column vector of length 2
%       PARAMS.b41 - column vector of length 2
%       PARAMS.b42 - column vector of length 2
%       PARAMS.b43 - column vector of length 2
%       PARAMS.b44 - column vector of length 2
%       PARAMS.b45 - column vector of length 2
%       PARAMS.b46 - column vector of length 2
%       PARAMS.b47 - column vector of length 2
%       PARAMS.b48 - column vector of length 2
%       PARAMS.b49 - column vector of length 2
%       PARAMS.b50 - column vector of length 2
%       PARAMS.C01 - matrix of size [11 x 14]
%       PARAMS.C02 - matrix of size [11 x 14]
%       PARAMS.C03 - matrix of size [11 x 14]
%       PARAMS.C04 - matrix of size [11 x 14]
%       PARAMS.C05 - matrix of size [11 x 14]
%       PARAMS.C06 - matrix of size [11 x 14]
%       PARAMS.C07 - matrix of size [11 x 14]
%       PARAMS.C08 - matrix of size [11 x 14]
%       PARAMS.C09 - matrix of size [11 x 14]
%       PARAMS.C10 - matrix of size [11 x 14]
%       PARAMS.C11 - matrix of size [11 x 14]
%       PARAMS.C12 - matrix of size [11 x 14]
%       PARAMS.C13 - matrix of size [11 x 14]
%       PARAMS.C14 - matrix of size [11 x 14]
%       PARAMS.C15 - matrix of size [11 x 14]
%       PARAMS.C16 - matrix of size [11 x 14]
%       PARAMS.C17 - matrix of size [11 x 14]
%       PARAMS.C18 - matrix of size [11 x 14]
%       PARAMS.C19 - matrix of size [11 x 14]
%       PARAMS.C20 - matrix of size [11 x 14]
%       PARAMS.C21 - matrix of size [11 x 14]
%       PARAMS.C22 - matrix of size [11 x 14]
%       PARAMS.C23 - matrix of size [11 x 14]
%       PARAMS.C24 - matrix of size [11 x 14]
%       PARAMS.C25 - matrix of size [11 x 14]
%       PARAMS.C26 - matrix of size [11 x 14]
%       PARAMS.C27 - matrix of size [11 x 14]
%       PARAMS.C28 - matrix of size [11 x 14]
%       PARAMS.C29 - matrix of size [11 x 14]
%       PARAMS.C30 - matrix of size [11 x 14]
%       PARAMS.C31 - matrix of size [11 x 14]
%       PARAMS.C32 - matrix of size [11 x 14]
%       PARAMS.C33 - matrix of size [11 x 14]
%       PARAMS.C34 - matrix of size [11 x 14]
%       PARAMS.C35 - matrix of size [11 x 14]
%       PARAMS.C36 - matrix of size [11 x 14]
%       PARAMS.C37 - matrix of size [11 x 14]
%       PARAMS.C38 - matrix of size [11 x 14]
%       PARAMS.C39 - matrix of size [11 x 14]
%       PARAMS.C40 - matrix of size [11 x 14]
%       PARAMS.C41 - matrix of size [11 x 14]
%       PARAMS.C42 - matrix of size [11 x 14]
%       PARAMS.C43 - matrix of size [11 x 14]
%       PARAMS.C44 - matrix of size [11 x 14]
%       PARAMS.C45 - matrix of size [11 x 14]
%       PARAMS.C46 - matrix of size [11 x 14]
%       PARAMS.C47 - matrix of size [11 x 14]
%       PARAMS.C48 - matrix of size [11 x 14]
%       PARAMS.C49 - matrix of size [11 x 14]
%       PARAMS.D01 - matrix of size [11 x 14]
%       PARAMS.D02 - matrix of size [11 x 14]
%       PARAMS.D03 - matrix of size [11 x 14]
%       PARAMS.D04 - matrix of size [11 x 14]
%       PARAMS.D05 - matrix of size [11 x 14]
%       PARAMS.D06 - matrix of size [11 x 14]
%       PARAMS.D07 - matrix of size [11 x 14]
%       PARAMS.D08 - matrix of size [11 x 14]
%       PARAMS.D09 - matrix of size [11 x 14]
%       PARAMS.D10 - matrix of size [11 x 14]
%       PARAMS.D11 - matrix of size [11 x 14]
%       PARAMS.D12 - matrix of size [11 x 14]
%       PARAMS.D13 - matrix of size [11 x 14]
%       PARAMS.D14 - matrix of size [11 x 14]
%       PARAMS.D15 - matrix of size [11 x 14]
%       PARAMS.D16 - matrix of size [11 x 14]
%       PARAMS.D17 - matrix of size [11 x 14]
%       PARAMS.D18 - matrix of size [11 x 14]
%       PARAMS.D19 - matrix of size [11 x 14]
%       PARAMS.D20 - matrix of size [11 x 14]
%       PARAMS.D21 - matrix of size [11 x 14]
%       PARAMS.D22 - matrix of size [11 x 14]
%       PARAMS.D23 - matrix of size [11 x 14]
%       PARAMS.D24 - matrix of size [11 x 14]
%       PARAMS.D25 - matrix of size [11 x 14]
%       PARAMS.D26 - matrix of size [11 x 14]
%       PARAMS.D27 - matrix of size [11 x 14]
%       PARAMS.D28 - matrix of size [11 x 14]
%       PARAMS.D29 - matrix of size [11 x 14]
%       PARAMS.D30 - matrix of size [11 x 14]
%       PARAMS.D31 - matrix of size [11 x 14]
%       PARAMS.D32 - matrix of size [11 x 14]
%       PARAMS.D33 - matrix of size [11 x 14]
%       PARAMS.D34 - matrix of size [11 x 14]
%       PARAMS.D35 - matrix of size [11 x 14]
%       PARAMS.D36 - matrix of size [11 x 14]
%       PARAMS.D37 - matrix of size [11 x 14]
%       PARAMS.D38 - matrix of size [11 x 14]
%       PARAMS.D39 - matrix of size [11 x 14]
%       PARAMS.D40 - matrix of size [11 x 14]
%       PARAMS.D41 - matrix of size [11 x 14]
%       PARAMS.D42 - matrix of size [11 x 14]
%       PARAMS.D43 - matrix of size [11 x 14]
%       PARAMS.D44 - matrix of size [11 x 14]
%       PARAMS.D45 - matrix of size [11 x 14]
%       PARAMS.D46 - matrix of size [11 x 14]
%       PARAMS.D47 - matrix of size [11 x 14]
%       PARAMS.D48 - matrix of size [11 x 14]
%       PARAMS.D49 - matrix of size [11 x 14]
%       PARAMS.D50 - matrix of size [11 x 14]
%       PARAMS.c02 - column vector of length 11
%       PARAMS.c03 - column vector of length 11
%       PARAMS.c04 - column vector of length 11
%       PARAMS.c05 - column vector of length 11
%       PARAMS.c06 - column vector of length 11
%       PARAMS.c07 - column vector of length 11
%       PARAMS.c08 - column vector of length 11
%       PARAMS.c09 - column vector of length 11
%       PARAMS.c10 - column vector of length 11
%       PARAMS.c11 - column vector of length 11
%       PARAMS.c12 - column vector of length 11
%       PARAMS.c13 - column vector of length 11
%       PARAMS.c14 - column vector of length 11
%       PARAMS.c15 - column vector of length 11
%       PARAMS.c16 - column vector of length 11
%       PARAMS.c17 - column vector of length 11
%       PARAMS.c18 - column vector of length 11
%       PARAMS.c19 - column vector of length 11
%       PARAMS.c20 - column vector of length 11
%       PARAMS.c21 - column vector of length 11
%       PARAMS.c22 - column vector of length 11
%       PARAMS.c23 - column vector of length 11
%       PARAMS.c24 - column vector of length 11
%       PARAMS.c25 - column vector of length 11
%       PARAMS.c26 - column vector of length 11
%       PARAMS.c27 - column vector of length 11
%       PARAMS.c28 - column vector of length 11
%       PARAMS.c29 - column vector of length 11
%       PARAMS.c30 - column vector of length 11
%       PARAMS.c31 - column vector of length 11
%       PARAMS.c32 - column vector of length 11
%       PARAMS.c33 - column vector of length 11
%       PARAMS.c34 - column vector of length 11
%       PARAMS.c35 - column vector of length 11
%       PARAMS.c36 - column vector of length 11
%       PARAMS.c37 - column vector of length 11
%       PARAMS.c38 - column vector of length 11
%       PARAMS.c39 - column vector of length 11
%       PARAMS.c40 - column vector of length 11
%       PARAMS.c41 - column vector of length 11
%       PARAMS.c42 - column vector of length 11
%       PARAMS.c43 - column vector of length 11
%       PARAMS.c44 - column vector of length 11
%       PARAMS.c45 - column vector of length 11
%       PARAMS.c46 - column vector of length 11
%       PARAMS.c47 - column vector of length 11
%       PARAMS.c48 - column vector of length 11
%       PARAMS.c49 - column vector of length 11
%       PARAMS.c50 - column vector of length 11
%       PARAMS.minusA_times_x0 - column vector of length 11
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.u0 - column vector of size 700
%
%   [OUTPUT, EXITFLAG] = mpcc(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - OPTIMAL solution has been found (subject to desired accuracy)
%       0 - Timeout - maximum number of iterations reached
%      -7 - Method could not progress. Problem may be infeasible. Run FORCESdiagnostics on your problem to check for most common errors in the formulation.
%    -100 - License error
%
%   [OUTPUT, EXITFLAG, INFO] = mpcc(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.pobj      - primal objective
%       INFO.dobj      - dual objective
%       INFO.dgap      - duality gap := pobj - dobj
%       INFO.rdgap     - relative duality gap := |dgap / pobj|
%       INFO.mu        - duality measure
%       INFO.sigma     - centering parameter
%       INFO.lsit_aff  - iterations of affine line search
%       INFO.lsit_cc   - iterations of line search (combined direction)
%       INFO.step_aff  - step size (affine direction)
%       INFO.step_cc   - step size (centering direction)
%       INFO.solvetime - Time needed for solve (wall clock time)
%
% See also COPYING
